### ISSUE TITLE
提几点模板的调整/优化建议( 对应版本v0.1.0, 2023.3.20)

### ISSUE THREAD

**Issue by now2roll** [zb-zombie/A-CSUST-Bachelor-thesis-template-based-on-LaTeX-system#13]
看得出来，作者凭一已之力，构建了这么大的架构，为母校争光添彩，可钦可敬！

顺便，提几点个人建议，对应相关的版本为：`v0.1.0`,`2023.3.20`

除了`thesis.tex`, 其余4个 主模块，似乎都没有 在页脚设置页码。在有多页需要 复印/装订的情况下，容易出现页码前后混乱。建议添加页码；

建议把`figure/`图片目录，拆分成2个：`logo/`专放校徽图案；`pic/`专放其它的个人素材图片。理由：`pic/`这几个字母，更容易理解。

部分校徽 logo 图案，文件名有点长。个人看了一下，常用的 logo 大约有4个，建议精简文件名命名规则：
- `csust_logo.pdf`(带校名文字；彩图)；
- `csust_logo_grey.pdf`(带校名文字；黑白图)；
- `csust_logo_lite.jpg`(精简版，即纯图案，不带校名文字；
- `csust_logo_lite_grey.pdf`(精简版，即纯图案，带校名文字；黑白图)；

至于其它的 LOGO，文件名建议也适当加以精简, 更通俗，更适应大众的理解习惯，如：

- `csustgreylogo_2640by2449.jpg` -> `csustgreylogo_2640x2449.jpg`

`slides/`目录下的`slides.tex`, 能否提升到上一级目录，方便共用`figure/`或`logo/`校徽图片？

`\setCJKmainfont{}[]{}`中文字体相关命令，建议字体名尽可能用 英文。必要时，可以加上中文注释。
理由：如果跨操作系统平台，Windows 下通常默认采用 gb2312 编码，如果在 Linux 或者 Mac 上编译 tex, 可能会因为文件编码未能正确识别，产生乱码或异常报错。

常用的中文字体，一般有两种：宋体，黑体。建议直接使用`\rm`和`\sf`， 或者`\songti`，`\heiti`命令直接指定。
尽可能少用`\setCJKmainfont{}`这种手工操作。理由：同样方便跨操作系统编译。

建议在导言区，添加一行命令，直接指定图片的多个搜索目录：`\graphicspath{{pic},{logo},{figure}}`

顺祝如意！

**Comment by jaxvanyang** [comment]
之前的目录确实有点混乱，计划将图片目录拆分成了 3 个子文件夹：
- `doc/`: 用于 README 的图片
- `template/`：用于本模板的图片
- `thesis/`：用于论文正文内容的图片

另外 slides 已经转移为新的独立项目：[csust-latex-sig/CSUSTGraduationSlides](https://github.com/csust-latex-sig/CSUSTGraduationSlides)。文件名就不改了，因为模板用到的图片一般也不会变更。

其它的我不太了解，就先不改动了。

**Comment by jaxvanyang** [comment]
暂时认为该 issue 已解决，后续有其它建议可以重新开启，感谢反馈。
