### ISSUE TITLE
19级学弟前来膜拜

### ISSUE THREAD

**Issue by ChenE2000** [zb-zombie/A-CSUST-Bachelor-thesis-template-based-on-LaTeX-system#15]
在Overflow上自己写了个很简单的模板https://www.overleaf.com/latex/templates/csust-undergraduate-thesis-latex-template/wtcxjknvzxhq，发布之后看到了18级学长的专业操作，十分佩服。

模板中的文字透露出一丝丝幽默，更多的则是专业的行事风格，学长牛逼的！

**Comment by Postroggy** [comment]
这是overleaf，不是overflow😂

**Comment by Zewbiee** [comment]
学弟能想到用 LaTeX 写毕设，并且在毕业前为长理贡献一份模板，我们也算是不谋而合了 ☺️ 👍
