### ISSUE TITLE
中文右括号有时候会被自动转成英文右括号

### ISSUE THREAD

**Issue by jaxvanyang** [zb-zombie/A-CSUST-Bachelor-thesis-template-based-on-LaTeX-system#16]
我在写论文的过程中发现有一个地方的 `（2）` 会被转成 `（2)`，中文右括号变成了英文右括号，但是这个 bug 并不能被稳定复现。在原模板中也存在一处 `（4）` 被转成了 `（4)`，但它前后也有几乎一样的 `（4）` 段落却都渲染正常，十分奇怪。

因为不能稳定复现所以排查起来有点困难，也许查看编译日志会有收获，该 issue 权当记录，看看有没有人能解决。

在 PDF 中被渲染成了英文右括号：

![image](https://github.com/zb-zombie/A-CSUST-Bachelor-thesis-template-based-on-LaTeX-system/assets/25650612/cacbfba3-9381-4aee-9cb4-49065c1566d2)

源码：

https://github.com/zb-zombie/A-CSUST-Bachelor-thesis-template-based-on-LaTeX-system/blob/ff97a63bfd5671fbe8ae97f1da013526f28c09d1/body/specification.tex#LL42C35-L42C35

**Comment by Zewbiee** [comment]
中文右括号不会变成英文右括号（可以复制粘贴到其他文本框确认），图中的 `（4）` 所在的那一行比较拥挤（为了使最后的文件名不断行所致），所以右括号与文字之间的间距被自动调整了，如果希望括号的间距不被调整，可以用 `\mbox` 命令包裹，比如 `\mbox{（4）}`.

**Comment by jaxvanyang** [comment]
> 中文右括号不会变成英文右括号（可以复制粘贴到其他文本框确认），图中的 `（4）` 所在的那一行比较拥挤（为了使最后的文件名不断行所致），所以右括号与文字之间的间距被自动调整了，如果希望括号的间距不被调整，可以用 `\mbox` 命令包裹，比如 `\mbox{（4）}`.

原来如此，感谢解答。
