### ISSUE TITLE
[BUG] 即使是短题目也会占用两行内容

### ISSUE THREAD

**Issue by jaxvanyang** [zb-zombie/A-CSUST-Bachelor-thesis-template-based-on-LaTeX-system#6]
像模板中很长的题目可以用 `\\` 来决定从哪分行，但很短的题目使用这种方法占用两行不太美观。

将横线改成根据内容行数自动增加是否可能？

![Screenshot from 2023-03-21 15-24-18](https://user-images.githubusercontent.com/25650612/226542000-be057224-32b8-4943-808b-8e1b863ba3de.png)
![Screenshot from 2023-03-21 15-23-56](https://user-images.githubusercontent.com/25650612/226542006-c8019af9-3244-4315-8e15-cce6153eb568.png)
![Screenshot from 2023-03-21 15-23-42](https://user-images.githubusercontent.com/25650612/226542009-bcb3dd56-b255-475a-b4b6-a34877b037ac.png)

**Comment by Zewbiee** [comment]
如果题目较短，想要隐藏下面的空行，可以将 [csustThesis.cls#L296](https://github.com/zb-zombie/A-CSUST-Bachelor-thesis-template-based-on-LaTeX-system/blob/main/csustThesis.cls#L296) 更改为
```latex
        \hspace*{\maxwidth}{\makebox[\titleBoxLen][l]{\phantom{幻影}}}
```
> 由于学校给的 word 模板本身有两条线，所以我直接写死了，自动化添加横线的方法肯定也是有的，不过我目前感觉没有实现的必要。

**Comment by jaxvanyang** [comment]
难怪，学校给的模板有更新，现在都是一条线，使用指南里面给的学校模板的链接已经打不开了，要不要建个仓库保存学校的模版防止失效？（我们都是老师发的，没去学校官网找）

**Comment by Zewbiee** [comment]
> 

<https://www.csust.edu.cn/jwc/info/1142/5294.htm>
现在可以打开吧？
题目只有一条线的有可能是更老的版本。

**Comment by jaxvanyang** [comment]
> > 
> 
> https://www.csust.edu.cn/jwc/info/1142/5294.htm 现在可以打开吧？ 题目只有一条线的有可能是更老的版本。

可以。不好意思我看错了，是老师发的让我们参考的任务书把多余的横线删了，模板还是有两条线的。

**Comment by jaxvanyang** [comment]
> 如果题目较短，想要隐藏下面的空行，可以将 [csustThesis.cls#L296](https://github.com/zb-zombie/A-CSUST-Bachelor-thesis-template-based-on-LaTeX-system/blob/main/csustThesis.cls#L296) 更改为
> 
> ```
>         \hspace*{\maxwidth}{\makebox[\titleBoxLen][l]{\phantom{幻影}}}
> ```

删除 `\underline` 后编译出来的格式没有变化，不过既然原来模板就是这样的话那就没必要纠结了，我的题目也不是很短。

**Comment by Zewbiee** [comment]
> 

昨天那个对应的是 `thesis.pdf` 封面的代码。

修改开题报告封面，可以将 [csustThesis.cls#L499](https://github.com/zb-zombie/A-CSUST-Bachelor-thesis-template-based-on-LaTeX-system/blob/main/csustThesis.cls#L499) 更改为

```latex
        \hspace*{\maxwidth}{\makebox[\titleBoxLen][l]{\phantom{幻影}}}
```

修改开题报告封面，可以将 [csustThesis.cls#L573](https://github.com/zb-zombie/A-CSUST-Bachelor-thesis-template-based-on-LaTeX-system/blob/main/csustThesis.cls#L573) 更改为

```latex
        \hspace*{\maxwidth}{\makebox[10cm][l]{\phantom{幻影}}}
```

> 这个需求以后也可以考虑做个选项。

**Comment by jaxvanyang** [comment]
@zb-zombie 
尝试了一下，这个我搞不定，不知道怎么实现的，学长有时间搞一下吧。
