### ISSUE TITLE
源文件中的缩进存在 tab 和空格混用的情况

### ISSUE THREAD

**Issue by jaxvanyang** [zb-zombie/A-CSUST-Bachelor-thesis-template-based-on-LaTeX-system#9]
例如在 `csustThesis.cls` 中，主要是用两个空格缩进，但是有些地方是用 tab 缩进的。

我习惯使用 tab 缩进，所以贡献的代码可能会加入 tab 缩进。不过这对编译出来的 PDF 格式没有影响，而且已有文件里也存在混用的情况，所以我只会尽量使用空格缩进，不保证不使用 tab。

如果后面对缩进有要求的话建议先把所有文件统一缩进格式。

**Comment by Zewbiee** [comment]
这个问题我确实没注意。
